### PR TITLE
update: Version 1.6.37

### PR DESCRIPTION
**Pull request by crashzk**
- Updated **README.md**
- Updated to version **1.6.37**;
- Fixed **`spaces`**;

### CODE REVIEW

**Comment by R1KO** [comment]
@crashzk thanks! but may be we will use spaces?

**Comment by crashzk** [comment]
@R1KO in case you prefer space? If yes, I can do this without any problems.

**Comment by R1KO** [comment]
> @R1KO in case you prefer space? If yes, I can do this without any problems.

if you don't mind, please

**Comment by crashzk** [comment]
@R1KO done, space applied.

**Pull request merged**
